# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 850b6cde04e7e95e932894083de8ce2598d2ce820b3c643154dfc6dbf3142cfad11f9687043ffde49074c7924fa23c0a7766ca0d2473720a94be77064fc9d939

test:
  secret_key_base: 593673b9fda7bd8b6d59a490df1fb84b737ea48c10f68c430acc5f45afd33f2d2404da71419809b66106066bcd50499bf864612e99da5499d224e48d65f1a537

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
